### ISSUE TITLE
Add Filter option in Verse Page

### ISSUE THREAD

**Issue by aarabii** [losier/bhagavadgitaapi#1]
Need to add a simple filter option in verse page that will help user to get a verse easily

**Comment by NewtonFernandis** [comment]
@losier Can you please assign this to me?
I will work on this

**Comment by aarabii** [comment]
Sure @NewtonFernandis i'll love to see your work 
Take your time to complete your work

**Comment by NewtonFernandis** [comment]
> Sure @NewtonFernandis i'll love to see your work Take your time to complete your work

Yep, sure
Thanks

**Comment by aarabii** [comment]
Thanks @NewtonFernandis
