### ISSUE TITLE
CREATE README

### ISSUE THREAD

**Issue by aarabii** [losier/bhagavadgitaapi#2]
Readme file suitable for the project

**Comment by the-amazing-atharva** [comment]
Hello!

I am a beginner to web dev and learning CSS right now, but would like to work on the README
If ok, do assign me to this issue!!!

**Comment by aarabii** [comment]
Sure i would love to see your work please let me know if you need any help with api endpoints @the-amazing-atharva

**Comment by the-amazing-atharva** [comment]
Thanks for the reply!!!

I dont know what APIs are yet but will research and learn about it and make a good README with time 👍

**Comment by aarabii** [comment]
@the-amazing-atharva 
in simple words Api(application programming interface)  means ```a piece of software that can be used
by another piece of software in order to allow application to talk to each other.```
If you face any dificulties you can leave the api section in readme 
else here is the url ```https://bhagavadgitaapi.vercel.app/api```
and endpoints are: 

- ```/shloks/id?=number``` where number will be from 1 to 701
- ```/audio``` this endpoint is still in progress so u can leave it
- ```/author```
- ```/chapter```
- ```/gita```
- ```/translation```
- ```/verse```
and please let me know if you need any help and you can leave the api section in readme if you want to

**Comment by the-amazing-atharva** [comment]
Thanks for the detailed info
Will work on the README step by step and let you know if I need more help :)

**Comment by the-amazing-atharva** [comment]
![Screenshot-2023-01-27-081018-transformed](https://user-images.githubusercontent.com/121221252/214999753-2f94daef-a3b9-4896-9a3a-efb806c8c1d0.png)

Can I add this as the logo in the README?

**Comment by aarabii** [comment]
Thanks @the-amazing-atharva for your work <3

**Comment by the-amazing-atharva** [comment]
Your welcome!

Will add more to the README soon
