### ISSUE TITLE
Documentation for API

### ISSUE THREAD

**Issue by aarabii** [losier/bhagavadgitaapi#5]
Need to create a Documentation for API

**Comment by the-amazing-atharva** [comment]
Hello bro!

I am a beginner to web dev and learning CSS right now, but would like to work on the README
If ok, do assign me to this issue!!!

**Comment by afrokayie** [comment]
Hello, I'd like to participate in creating documentation for your API. Could you share materials that could help me get familiar with the project?

**Comment by aarabii** [comment]
I'm really sorry @afrokayie,
This repo is no more active and the APIs are also not working properly 
and I'm really sorry I forgot yo private this repo
